{
 "title": "EcoFlow",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "SerialNumber",
    "label": "Serial Number",
    "query": {
     "query": "show tag values with key=\"SerialNumber\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State of Charge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Battery",
     "select": [
      [
       { "params": [ "StateOfCharge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Energy Sources",
   "type": "stat",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$B / $A", "type": "math" },
    { "expression": "$C / $A", "type": "math" },
    { "expression": "1 - (($B + $C) / $A)", "type": "math" }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "TotalOutWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Energy Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "TotalSolarWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Solar  In" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "InverterInWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Grid In" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    },
    { "expression": "$A - $B - $C", "type": "math" }
   ]
  },
  {
   "title": "Energy",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "TotalOutWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Energy Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "InverterInWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Grid In" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "TotalSolarWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Solar In" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    },
    { "expression": "$A - $B - $C", "type": "math" }
   ]
  },
  {
   "title": "State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Battery",
     "select": [
      [
       { "params": [ "StateOfCharge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Inverter",
     "select": [
      [
       { "params": [ "InputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Input Watts" ], "type": "alias" }
      ],
      [
       { "params": [ "OutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Output Watts" ], "type": "alias" }
      ],
      [
       { "params": [ "OutAmps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Output Amps" ], "type": "alias" }
      ],
      [
       { "params": [ "OutVolts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Output Volts" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Power In and Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "TotalInWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" },
       { "params": [ "Total In" ], "type": "alias" }
      ],
      [
       { "params": [ "TotalOutWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Inverter Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Inverter",
     "select": [
      [
       { "params": [ "InputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Input Watts" ], "type": "alias" }
      ],
      [
       { "params": [ "OutputWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Output Watts" ], "type": "alias" }
      ],
      [
       { "params": [ "AcInVolts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "AC In Volts" ], "type": "alias" }
      ],
      [
       { "params": [ "AcInAmps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "AC in Amps" ], "type": "alias" }
      ],
      [
       { "params": [ "OutAmps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Out Amps" ], "type": "alias" }
      ],
      [
       { "params": [ "OutVolts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Out Volts" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Solar Generation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Power",
     "query": "SELECT mean(\"Solar1Watts\"), Mean(\"Solar2Watts\"), Mean(\"TotalSolarWatts\") FROM \"Power\" WHERE (\"SerialNumber\"::tag =~ /^$SerialNumber$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Solar1Watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Solar 1" ], "type": "alias" }
      ],
      [
       { "params": [ "Solar2Watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Solar 2" ], "type": "alias" }
      ],
      [
       { "params": [ "TotalSolarWatts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SerialNumber::tag", "operator": "=~", "value": "/^$SerialNumber$/" }
     ]
    }
   ]
  }
 ]
}